name: Deploy to Netlify

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Build
        run: npm run build

      - name: Debug Netlify secrets
        run: |
          if [ -z "${NETLIFY_AUTH_TOKEN}" ]; then
            echo "NETLIFY_AUTH_TOKEN está VAZIO"
          else
            echo "NETLIFY_AUTH_TOKEN está DEFINIDO"
          fi
          if [ -z "${NETLIFY_SITE_ID}" ]; then
            echo "NETLIFY_SITE_ID está VAZIO"
          else
            echo "NETLIFY_SITE_ID está DEFINIDO"
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './out'
          production-branch: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
